import { useEffect, useState } from 'react';
import { Position, ReactFlow, type Edge, type Node } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import type { Workflow } from '../graph/types';
import { layoutWorkflow, type LaidOutGraph } from '../graph/layout';
import { planBackEdges } from '../graph/backEdge';
import { SignalNode } from './SignalNode';
import { SignalEdge } from './SignalEdge';
import './canvas.css';

const nodeTypes = { signal: SignalNode };
const edgeTypes = { signal: SignalEdge };

export function GraphCanvas({ workflow }: { workflow: Workflow }) {
  const [laidOut, setLaidOut] = useState<LaidOutGraph | null>(null);

  useEffect(() => {
    let live = true;
    layoutWorkflow(workflow).then((g) => {
      if (live) setLaidOut(g);
    });
    return () => {
      live = false;
    };
  }, [workflow]);

  if (!laidOut) {
    return (
      <div className="sg-canvas sg-canvas--loading" data-testid="canvas-loading">
        COMPILING GRAPH…
      </div>
    );
  }

  const nodes: Node[] = laidOut.nodes.map((n, i) => ({
    id: n.id,
    type: 'signal',
    position: { x: n.x, y: n.y },
    // Dimensions are known ahead of measurement — ELK laid the graph out
    // against exactly these numbers. Supplying them means the first paint has
    // correct bounds (no measure round-trip, no hidden nodes) and the edge
    // layer renders immediately instead of waiting on a ResizeObserver tick.
    width: n.width,
    height: n.height,
    // Handle geometry, likewise known ahead of measurement: SignalNode puts a
    // target port at the left edge middle and a source port at the right edge
    // middle (flow runs left→right). React Flow prefers measured bounds when it
    // has them (`internals.handleBounds || toHandleBounds`), so this only fills
    // the gap before the first ResizeObserver tick — without it RF declines to
    // render the edge layer at all.
    handles: [
      { type: 'target', position: Position.Left, x: 0, y: n.height / 2 },
      { type: 'source', position: Position.Right, x: n.width, y: n.height / 2 },
    ],
    data: { node: n.node, index: i },
    draggable: false,
    connectable: false,
    selectable: false,
  }));

  // Reversed edges need to know about cards they never touch, so their return
  // route is planned here — the one place that can see the whole layout — and
  // handed to SignalEdge as data.
  const backPlan = planBackEdges(laidOut.nodes, laidOut.edges);

  const edges: Edge[] = laidOut.edges.map((e, i) => ({
    id: e.id,
    source: e.from,
    target: e.to,
    type: 'signal',
    // no points: SignalEdge curves between the ports React Flow reports, so
    // ELK's spline sections are not carried into the render
    data: { kind: e.kind, label: e.label, index: i, back: backPlan.get(e.id) },
  }));

  const { meta } = workflow;
  // reduce, not Math.max(...spread): a node-less graph answers 0 rather than
  // -Infinity, so the pain readout degrades to no dots instead of throwing.
  const maxPain = workflow.nodes.reduce((m, n) => Math.max(m, n.painLevel), 0);

  return (
    <div className="sg-canvas" data-testid="canvas">
      <svg className="sg-defs" aria-hidden="true">
        <defs>
          <marker id="fp-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="8" markerHeight="8" orient="auto-start-reverse">
            <path d="M 0 0 L 8 4 L 0 8" fill="none" stroke="context-stroke" strokeWidth="1.5" />
          </marker>
        </defs>
      </svg>
      <div className="sg-toolbar" data-testid="canvas-toolbar">
        <span className="sg-wf-title">{meta.title}</span>
        <span className="sg-chip">
          <b>{workflow.nodes.length}</b> nodes
        </span>
        <span className="sg-chip">
          max pain <span className="sg-chip-hot">{'●'.repeat(maxPain)}</span>
        </span>
        <span className="sg-chip">{meta.kbSource === 'airtable' ? 'AIRTABLE' : 'KB NOT LINKED'}</span>
        <span className="sg-chip sg-chip--end">
          generated by <b>{meta.model}</b>
        </span>
      </div>
      <div className="sg-viewport">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          nodeTypes={nodeTypes}
          edgeTypes={edgeTypes}
          fitView
          fitViewOptions={{ padding: 0.12 }}
          minZoom={0.2}
          maxZoom={2}
          nodesDraggable={false}
          nodesConnectable={false}
          elementsSelectable={false}
          proOptions={{ hideAttribution: true }}
        />
      </div>
    </div>
  );
}
