import { render, screen, waitFor } from '@testing-library/react';
import gallery from '../../../gallery/add-e2e-tests.workflow.json';
import { loadWorkflow } from '../graph/load';
import { GraphCanvas } from './GraphCanvas';

const wf = (() => {
  const res = loadWorkflow(gallery);
  if (!res.ok) throw new Error('fixture invalid');
  return res.workflow;
})();

const maxPain = wf.nodes.reduce((m, n) => Math.max(m, n.painLevel), 0);

it('lays out and renders every node on the canvas', async () => {
  render(<GraphCanvas workflow={wf} />);
  await waitFor(() => {
    expect(screen.getAllByTestId('sg-node')).toHaveLength(wf.nodes.length);
  });
  expect(screen.getByTestId('canvas')).toBeInTheDocument();
});

it('reads COMPILING GRAPH… until the layout resolves', () => {
  // The layout engine is async, so the very first paint is always the loading
  // state — asserted synchronously, before the ELK promise settles.
  render(<GraphCanvas workflow={wf} />);
  expect(screen.getByTestId('canvas-loading')).toHaveTextContent('COMPILING GRAPH…');
  expect(screen.queryByTestId('canvas-toolbar')).not.toBeInTheDocument();
});

it('states the graph in the toolbar: title, counts, pain, KB, model', async () => {
  render(<GraphCanvas workflow={wf} />);
  await waitFor(() => {
    expect(screen.getAllByTestId('sg-node')).toHaveLength(wf.nodes.length);
  });

  // natural case — the title is the author's, not a filing-cabinet caption
  expect(screen.getByText(wf.meta.title)).toBeInTheDocument();
  expect(screen.getByText('KB NOT LINKED')).toBeInTheDocument();

  const toolbar = screen.getByTestId('canvas-toolbar');
  expect(toolbar).toHaveTextContent(`${wf.nodes.length} nodes`);
  expect(toolbar).toHaveTextContent(`max pain ${'●'.repeat(maxPain)}`);
  expect(toolbar).toHaveTextContent(`generated by ${wf.meta.model}`);
});

it('plots every edge through React Flow and keeps the labels', async () => {
  const { container } = render(<GraphCanvas workflow={wf} />);
  await waitFor(() => {
    expect(screen.getAllByTestId('sg-node')).toHaveLength(wf.nodes.length);
  });

  // the whole edge layer reaches the DOM through the real React Flow pipeline
  expect(container.querySelectorAll('path.sg-edge')).toHaveLength(wf.edges.length);
  expect(screen.getByText('CI green')).toBeInTheDocument();
});

// The old chrome hung extra layers off the root — a frame, two rulers, a
// caption block. Pinning the child list keeps that habit from creeping back:
// the canvas is a marker def, a toolbar, and the graph itself. Nothing else.
it('hangs nothing off the root but the defs, the toolbar, and the viewport', async () => {
  render(<GraphCanvas workflow={wf} />);
  await waitFor(() => {
    expect(screen.getAllByTestId('sg-node')).toHaveLength(wf.nodes.length);
  });

  const canvas = screen.getByTestId('canvas');
  expect([...canvas.children].map((el) => el.getAttribute('class'))).toEqual([
    'sg-defs',
    'sg-toolbar',
    'sg-viewport',
  ]);
});
