import { createEvent, fireEvent, render, screen, waitFor } from '@testing-library/react';
import gallery from '../../../gallery/add-e2e-tests.workflow.json';
import enrichedDoc from '../test/fixtures/enriched.workflow.json';
import { loadWorkflow } from '../graph/load';
import type { Workflow } from '../graph/types';
import { GraphCanvas } from './GraphCanvas';

function fixture(raw: unknown, what: string): Workflow {
  const res = loadWorkflow(raw);
  if (!res.ok) throw new Error(`${what} fixture invalid: ${res.errors.join('; ')}`);
  return res.workflow;
}

const wf = fixture(gallery, 'gallery');
/** The KB-matched graph: two suggestions on one node, one patch the reducer refuses. */
const enriched = fixture(enrichedDoc, 'enriched');

const maxPain = wf.nodes.reduce((m, n) => Math.max(m, n.painLevel), 0);

/**
 * Waits out the async ELK pass and hands back the painted cards. The generous
 * timeout is for the layout, not for flakiness: a whole ELK run sits between the
 * render and the first card, and on a loaded machine that outlasts the 1s
 * default long before anything is actually wrong.
 */
const LAYOUT_WAIT = { timeout: 5000 };

async function cardsOf(graph: Workflow): Promise<HTMLElement[]> {
  await waitFor(() => {
    expect(screen.getAllByTestId('sg-node')).toHaveLength(graph.nodes.length);
  }, LAYOUT_WAIT);
  return screen.getAllByTestId('sg-node');
}

const cards = () => cardsOf(wf);

function cardFor(label: string, all: HTMLElement[]): HTMLElement {
  const card = all.find((el) => el.textContent?.includes(label));
  if (!card) throw new Error(`no card for ${label}`);
  return card;
}

it('lays out and renders every node on the canvas', async () => {
  render(<GraphCanvas workflow={wf} />);
  await waitFor(() => {
    expect(screen.getAllByTestId('sg-node')).toHaveLength(wf.nodes.length);
  });
  expect(screen.getByTestId('canvas')).toBeInTheDocument();
});

it('reads COMPILING GRAPH… until the layout resolves', () => {
  // The layout engine is async, so the very first paint is always the loading
  // state — asserted synchronously, before the ELK promise settles.
  render(<GraphCanvas workflow={wf} />);
  expect(screen.getByTestId('canvas-loading')).toHaveTextContent('COMPILING GRAPH…');
  expect(screen.queryByTestId('canvas-toolbar')).not.toBeInTheDocument();
});

it('states the graph in the toolbar: title, counts, pain, KB, model', async () => {
  render(<GraphCanvas workflow={wf} />);
  await waitFor(() => {
    expect(screen.getAllByTestId('sg-node')).toHaveLength(wf.nodes.length);
  });

  // natural case — the title is the author's, not a filing-cabinet caption
  expect(screen.getByText(wf.meta.title)).toBeInTheDocument();
  expect(screen.getByText('KB NOT LINKED')).toBeInTheDocument();

  const toolbar = screen.getByTestId('canvas-toolbar');
  expect(toolbar).toHaveTextContent(`${wf.nodes.length} nodes`);
  expect(toolbar).toHaveTextContent(`max pain ${'●'.repeat(maxPain)}`);
  expect(toolbar).toHaveTextContent(`generated by ${wf.meta.model}`);
});

it('plots every edge through React Flow and keeps the labels', async () => {
  const { container } = render(<GraphCanvas workflow={wf} />);
  await waitFor(() => {
    expect(screen.getAllByTestId('sg-node')).toHaveLength(wf.nodes.length);
  });

  // the whole edge layer reaches the DOM through the real React Flow pipeline
  expect(container.querySelectorAll('path.sg-edge')).toHaveLength(wf.edges.length);
  expect(screen.getByText('CI green')).toBeInTheDocument();
});

// The old chrome hung extra layers off the root — a frame, two rulers, a
// caption block. Pinning the child list keeps that habit from creeping back:
// the canvas is a marker def, a toolbar, and the graph itself. Nothing else.
it('hangs nothing off the root but the defs, the toolbar, and the viewport', async () => {
  render(<GraphCanvas workflow={wf} />);
  await waitFor(() => {
    expect(screen.getAllByTestId('sg-node')).toHaveLength(wf.nodes.length);
  });

  const canvas = screen.getByTestId('canvas');
  expect([...canvas.children].map((el) => el.getAttribute('class'))).toEqual([
    'sg-defs',
    'sg-toolbar',
    'sg-viewport',
  ]);
});

// React Flow 12 stamps `draggable` (and its own `nopan`) onto the node wrapper
// exactly when that node may be dragged — see NodeWrapper's class list. Pinning
// the emitted class is how we hold `nodesDraggable` on without reaching into
// React Flow's store.
it('hands every card to React Flow as draggable and selectable', async () => {
  const { container } = render(<GraphCanvas workflow={wf} />);
  await cards();

  expect(container.querySelectorAll('.react-flow__node.draggable')).toHaveLength(wf.nodes.length);
  expect(container.querySelectorAll('.react-flow__node.selectable')).toHaveLength(wf.nodes.length);
  // reshaping the layout is not rewiring the workflow — ports stay inert
  expect(container.querySelectorAll('.react-flow__handle.connectable')).toHaveLength(0);
});

it('opens the detail drawer on the clicked node', async () => {
  const target = wf.nodes.find((n) => n.painLevel === 5)!;
  render(<GraphCanvas workflow={wf} />);
  const all = await cards();

  expect(screen.queryByTestId('detail-drawer')).not.toBeInTheDocument();
  fireEvent.click(cardFor(target.label, all));

  const drawer = await screen.findByTestId('detail-drawer');
  expect(drawer).toHaveTextContent(target.label);
  expect(drawer).toHaveTextContent(target.description);
  expect(drawer).toHaveTextContent(target.kind);
});

/**
 * One step of a press-slip-release-click gesture, with `event.view` populated.
 *
 * Real pointers slip, and React Flow hands `nodeClickDistance` to d3-drag, which
 * swallows the trailing click of any gesture that travelled further. d3-drag
 * works in mouse events, so the whole gesture is reachable from jsdom — with one
 * catch: it binds its mousemove/mouseup listeners to `event.view` and hands that
 * same window to `yesdrag`, which is what installs (or doesn't) the click guard.
 * jsdom's MouseEvent constructor refuses a `view` member here, so it is defined
 * on the instance instead. That field is the only thing supplied by hand;
 * everything the assertions depend on is real d3-drag driving real React Flow.
 */
function mouse(
  type: 'mouseDown' | 'mouseMove' | 'mouseUp' | 'click',
  target: Element | Window,
  x: number,
) {
  const event = createEvent[type](target, { clientX: x, clientY: 100, button: 0 });
  Object.defineProperty(event, 'view', { value: window });
  fireEvent(target, event);
}

function gesture(el: HTMLElement, dx: number) {
  mouse('mouseDown', el, 100);
  mouse('mouseMove', window, 100 + dx);
  mouse('mouseUp', window, 100 + dx);
  // synchronous: d3 tears its click guard down on the next tick
  mouse('click', el, 100 + dx);
}

// Regression: at the 0 default a CDP pointer probe measured a 1px wobble killing
// the click outright, so the headline interaction of the whole phase silently
// no-opped on any real mouse. This test goes red again if the tolerance is
// dropped; its sibling below holds the other end — a real drag stays silent.
it('still opens the drawer when the click slips a few pixels', async () => {
  render(<GraphCanvas workflow={wf} />);
  const all = await cards();

  gesture(cardFor(wf.nodes[0].label, all), 3);
  expect(await screen.findByTestId('detail-drawer')).toHaveTextContent(wf.nodes[0].label);
});

it('stays silent when the gesture is a real drag', async () => {
  render(<GraphCanvas workflow={wf} />);
  const all = await cards();

  gesture(cardFor(wf.nodes[0].label, all), 120);
  expect(screen.queryByTestId('detail-drawer')).not.toBeInTheDocument();
});

it('rings the clicked card with the accent selection state', async () => {
  const target = wf.nodes[0];
  render(<GraphCanvas workflow={wf} />);
  const all = await cards();

  fireEvent.click(cardFor(target.label, all));
  await waitFor(() => {
    expect(cardFor(target.label, screen.getAllByTestId('sg-node')).className).toContain(
      'sg-node--selected',
    );
  });
  expect(document.querySelectorAll('.sg-node--selected')).toHaveLength(1);
});

it('closes the drawer on Escape', async () => {
  render(<GraphCanvas workflow={wf} />);
  const all = await cards();

  fireEvent.click(cardFor(wf.nodes[0].label, all));
  await screen.findByTestId('detail-drawer');

  fireEvent.keyDown(window, { key: 'Escape' });
  await waitFor(() => {
    expect(screen.queryByTestId('detail-drawer')).not.toBeInTheDocument();
  });
});

it('closes the drawer when the canvas behind it is clicked', async () => {
  const { container } = render(<GraphCanvas workflow={wf} />);
  const all = await cards();

  fireEvent.click(cardFor(wf.nodes[0].label, all));
  await screen.findByTestId('detail-drawer');

  fireEvent.click(container.querySelector('.react-flow__pane')!);
  await waitFor(() => {
    expect(screen.queryByTestId('detail-drawer')).not.toBeInTheDocument();
  });
});

it('offers RESET LAYOUT, which puts a moved node back and drops the selection', async () => {
  const { container } = render(<GraphCanvas workflow={wf} />);
  const all = await cards();

  const reset = screen.getByTestId('reset-layout');
  expect(reset).toHaveTextContent('RESET LAYOUT');

  const moved = wf.nodes[0];
  const wrapper = container.querySelector<HTMLElement>(`.react-flow__node[data-id="${moved.id}"]`)!;
  const pristine = wrapper.style.transform;

  const card = cardFor(moved.label, all);
  fireEvent.click(card);
  await screen.findByTestId('detail-drawer');
  for (let i = 0; i < 5; i++) {
    fireEvent.keyDown(card, { key: 'ArrowDown', shiftKey: true });
  }
  await waitFor(() => {
    expect(wrapper.style.transform).not.toBe(pristine);
  });

  fireEvent.click(reset);
  await waitFor(() => {
    expect(screen.queryByTestId('detail-drawer')).not.toBeInTheDocument();
  });
  // the graph comes back exactly as ELK first drew it, with nothing selected —
  // a second full layout pass, so it waits on the layout budget
  await waitFor(() => {
    expect(
      container.querySelector<HTMLElement>(`.react-flow__node[data-id="${moved.id}"]`)!.style
        .transform,
    ).toBe(pristine);
  }, LAYOUT_WAIT);
  await cards();
  expect(document.querySelectorAll('.sg-node--selected')).toHaveLength(0);
});

// The return lanes are planned against the cards they must clear, so their input
// is the LIVE node positions — not the frozen ELK result. Push a card down and
// the floor under the run has to follow it. React Flow's own keyboard nudge is
// the honest way to move a node here: it runs the same position pipeline a mouse
// drag does, without asking jsdom to fake pointer capture.
it('replans the back-edge floors from live positions when a node moves', async () => {
  const { container } = render(<GraphCanvas workflow={wf} />);
  const all = await cards();

  // back-edge routes are the only ones built from quadratic corners
  const backPaths = () =>
    [...container.querySelectorAll<SVGPathElement>('path.sg-edge')]
      .map((p) => p.getAttribute('d') ?? '')
      .filter((d) => d.includes('Q'));

  const before = backPaths();
  expect(before.length).toBeGreaterThan(0);

  const card = cardFor(wf.nodes.find((n) => n.id === 'debug-flaky')!.label, all);
  fireEvent.click(card);
  for (let i = 0; i < 40; i++) {
    fireEvent.keyDown(card, { key: 'ArrowDown', shiftKey: true });
  }

  // the card now hangs far below every other row, so every run crossing its
  // column has to drop under it
  await waitFor(() => {
    expect(backPaths()).not.toEqual(before);
  });
});

// ---------------------------------------------------------------------------
// Suggestions on the graph
// ---------------------------------------------------------------------------

const VERIFY = 'Verify it by hand in the browser';
const SCAFFOLD = 'Scaffold the module & wire it up';

it('pips only the cards the KB matched, with the count it matched', async () => {
  const { container } = render(<GraphCanvas workflow={enriched} />);
  await cardsOf(enriched);

  const pip = (id: string) =>
    container.querySelector(`.react-flow__node[data-id="${id}"] [data-testid="sg-badge"]`);

  expect(pip('verify-browser')).toHaveTextContent('2');
  expect(pip('research-docs')).toHaveTextContent('1');
  expect(pip('scaffold-repo')).toHaveTextContent('1');
  expect(pip('write-code')).toBeNull();
  expect(pip('gather-brief')).toBeNull();
  expect(screen.getAllByTestId('sg-badge')).toHaveLength(3);
});

it('leaves every card bare on a graph with no KB behind it', async () => {
  render(<GraphCanvas workflow={wf} />);
  await cards();
  expect(screen.queryByTestId('sg-badge')).not.toBeInTheDocument();
});

// The drawer is the only route to a suggestion, so it cannot be mouse-only.
// React Flow already focuses cards and selects them on Enter/Space; what it does
// not do is tell us about it, so the canvas listens for the same keys.
it('opens the drawer from the keyboard, with no pointer involved', async () => {
  const { container } = render(<GraphCanvas workflow={enriched} />);
  await cardsOf(enriched);

  const wrapper = container.querySelector<HTMLElement>(
    '.react-flow__node[data-id="verify-browser"]',
  )!;
  wrapper.focus();
  expect(document.activeElement).toBe(wrapper);

  fireEvent.keyDown(wrapper, { key: 'Enter' });
  expect(await screen.findByTestId('detail-drawer')).toHaveTextContent(VERIFY);
});

it('takes Space as well as Enter', async () => {
  const { container } = render(<GraphCanvas workflow={enriched} />);
  await cardsOf(enriched);

  const wrapper = container.querySelector<HTMLElement>(
    '.react-flow__node[data-id="gather-brief"]',
  )!;
  wrapper.focus();
  fireEvent.keyDown(wrapper, { key: ' ' });
  expect(await screen.findByTestId('detail-drawer')).toHaveTextContent(
    'Gather the brief & acceptance criteria',
  );
});

it('ignores the keys when the focus is not on a card', async () => {
  render(<GraphCanvas workflow={enriched} />);
  await cardsOf(enriched);

  const reset = screen.getByTestId('reset-layout');
  reset.focus();
  fireEvent.keyDown(reset, { key: 'Enter' });
  expect(screen.queryByTestId('detail-drawer')).not.toBeInTheDocument();
});

// Two rows can upgrade the same step; the canvas dry-runs each patch on its own,
// so neither sibling is dimmed by the other's existence.
it('finds both siblings on one node appliable', async () => {
  render(<GraphCanvas workflow={enriched} />);
  const all = await cardsOf(enriched);

  fireEvent.click(cardFor(VERIFY, all));
  await screen.findByTestId('detail-drawer');

  const buttons = screen.getAllByTestId('sg-sug-apply');
  expect(buttons).toHaveLength(2);
  for (const b of buttons) expect(b).toBeEnabled();
  expect(screen.queryByTestId('sg-sug-invalid')).not.toBeInTheDocument();
});

// The fixture's scaffold patch passes the schema and still breaks the graph: it
// deletes the step, then wires an edge back into it. The reducer refuses, the dry
// run hears the refusal, and the card says so rather than offering a button that
// throws.
it('marks the patch the reducer refuses as invalid', async () => {
  render(<GraphCanvas workflow={enriched} />);
  const all = await cardsOf(enriched);

  fireEvent.click(cardFor(SCAFFOLD, all));
  await screen.findByTestId('detail-drawer');

  expect(screen.getByTestId('sg-sug-apply')).toBeDisabled();
  expect(screen.getByTestId('sg-sug-invalid')).toHaveTextContent('PATCH INVALID');
});

// Task 5 owns the morph. Until it lands, pressing APPLY is inert — pinned so a
// half-wired handler cannot quietly mutate the graph in the meantime.
it('leaves the graph alone when APPLY is pressed — the morph is Task 5', async () => {
  render(<GraphCanvas workflow={enriched} />);
  const all = await cardsOf(enriched);

  fireEvent.click(cardFor(VERIFY, all));
  await screen.findByTestId('detail-drawer');

  fireEvent.click(screen.getAllByTestId('sg-sug-apply')[0]);
  expect(screen.getAllByTestId('sg-node')).toHaveLength(enriched.nodes.length);
  expect(screen.getAllByTestId('sg-badge')).toHaveLength(3);
});
